services:
  backend:
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm start

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: builder  # Use the builder stage which has Node.js
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - /app/node_modules
    command: npm start
    ports:
      - "3000:3000"  # Override port mapping for dev server