
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: devops-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    env_file:
      - ./backend/.env
    networks:
      - devops-network
    volumes:
      - backend-logs:/app/logs
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.devops.service=backend"
      - "com.devops.description=Backend API service"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: devops-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    networks:
      - devops-network
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - frontend-logs:/var/log/nginx
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.devops.service=frontend"
      - "com.devops.description=Frontend React application"

networks:
  devops-network:
    driver: bridge
    name: devops-network

volumes:
  backend-logs:
    name: devops-backend-logs
  frontend-logs:
    name: devops-frontend-logs
