global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Your backend service
  - job_name: 'devops-backend'
    static_configs:
      - targets: ['devops-backend:3001']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['devops-node-exporter:9100']
    scrape_interval: 5s

  # Add more services here as needed
  # - job_name: 'devops-frontend'
  #   static_configs:
  #     - targets: ['devops-frontend:3000']